// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW47wIqAaUEpinfM9J9zkk4jymIT58-RI',
    appId: '1:429308860871:web:2a2ab35e95cf9e0de0a1e2',
    messagingSenderId: '429308860871',
    projectId: 'flutter-chat-f2149',
    authDomain: 'flutter-chat-f2149.firebaseapp.com',
    storageBucket: 'flutter-chat-f2149.appspot.com',
    measurementId: 'G-ZWFNCP2966',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJywtkXDQFlRF-RUh_0Zc-du0SpD0jHk',
    appId: '1:429308860871:android:072b80c768f92e2ee0a1e2',
    messagingSenderId: '429308860871',
    projectId: 'flutter-chat-f2149',
    storageBucket: 'flutter-chat-f2149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-HHEhD4n9bja_AgXielbPlLUYEtF8P8',
    appId: '1:429308860871:ios:983fd87ecec1f706e0a1e2',
    messagingSenderId: '429308860871',
    projectId: 'flutter-chat-f2149',
    storageBucket: 'flutter-chat-f2149.appspot.com',
    iosBundleId: 'com.example.section14',
  );
}
